# -*- coding: utf-8 -*-
"""Week_02_E_Commerce_site_Nihal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lWwiXQhsW7P0fHwHkRLDxdN94kZS283x
"""

##################   1.1_Ecommerce-system (Simple)   #########################

# ----------------- Product --------------------
# Simple product class: products can be added with only a name and class

class Product:

  def __init__(self, name,price):  #initialize
    self.name = name
    self.price = price

# ----------------- Cart ----------------------
#Simple cart class : product objects can only be
# added to the cart class' list(empty at first, like an empty cart),
# or removed.
#you can also check total price of products

class Cart:
  def __init__(self):   #initialize
    self.items = []

  def add_item(self,product):
    self.items.append(product)

  def remove_item(self,product):
    self.items.remove(product)

  def check_total(self):
    total = 0
    for item in self.items:
      total += item.price
    print(total)


# ---------------- Implementation ----------------
#Seller adds product to sell
item1 = Product("Apple", 15)
item2 = Product ("Banana" , 10)
item3 = Product("Men woven shirt" , 50)

#User  add/removes products in cart, checks total after
cart1 = Cart()
cart1.add_item(item1)
cart1.add_item(item2)
cart1.add_item(item3)
cart1.remove_item(item1)
cart1.check_total()

##################   1.2_Ecommerce-system (Upgraded)   #########################

#------------------------ Patch Notes ----------------------------
# Upgrades (Products) :
#     -can now assign a unique ID to each product
#     -added method to display product info to the user
#     -products can now be categorized vis subtype classes
# Added new features : Users!
# Upgrades (Cart) :
#     -create account for personalized sessions
#     -can now validate item deletions by ID
#     -added a checkout option
#------------------------ Patch Notes ----------------------------


#=========================================================================
#                               BACKEND
#=========================================================================


#_________________________PRODUCT__________________________
class Product:
  def __init__ (self, product_id, name,price):
    self.product_id = product_id
    self.name = name
    self.price = price

  def display_product(self):
    print(f"ID: {self.product_id}, Name: {self.name}, Price: ${self.price:.2f}")

#Subclasses

class Book(Product):
    def __init__(self, product_id , name, price,author):
      super().__init__(product_id,name,price)
      self.author = author
#_________________________PRODUCT_______________________


#___________________________USER________________________

class User:
  def __init__ (self,username,password):
    self.username = username
    self.password = password
#___________________________USER_________________________


#___________________________CART_________________________
class Cart:
  def __init__(self):
    self.items = []

  def add_item(self,product):
    self.items.append(product)

  def remove_item(self,product_id):
    for item in self.items:
      if item.product_id == product_id:
        self.items.remove(item)
        print(f"Item {product_id} removed from cart.")
        return
    print(f"Item {product_id} not found in cart")

  def check_total(self):
    total = 0
    for item in self.items:
      total += item.price
    return total

  def checkout(self):
    total = self.check_total()
    print(f"Total : ${total}")
    print("Checkout successful! Thanks for your purchase!")
    self.items.clear()
  #___________________________CART___________________________

#======================================================================
#                            FRONT-END
#======================================================================

#_________ Seller : lists items to sell (Product class) ______

book1 = Book(101, "Python Basics", 25, "John Smith")
item2 = Product(2, "T-shirt" , 20)
item3 = Product(3, "Women woven scarf" , 99)

#_________ _____________________________________________ ______


#_________ User : make account (user class) __________________

User ("HyperKnight67","Python123@")

#__________ _____________________________________________ ____


#___________ User : starts shopping (cart class) _____________

cart_1 = Cart()

cart_1.add_item(book1)
cart_1.add_item(item2)
cart_1.add_item(item3)

print(cart_1.check_total())

cart_1.remove_item(101)

print(cart_1.check_total())

cart_1.checkout()

#__________ _____________________________________________ ____

##################   1.3_Ecommerce-system (Interactive)   #########################

#------------------------ Patch Notes ----------------------------
# Added features:
# polished front end , user's can actually interact without coding
# and add, remove, check product details and so on from just clicking
# on a series of predetermined menu options!
#------------------------ Patch Notes ----------------------------

#_________________________PRODUCT__________________________
class Product:
  def __init__ (self, product_id, name,price):
    self.product_id = product_id
    self.name = name
    self.price = price

  def display_product(self):
    print(f"ID: {self.product_id}, Name: {self.name}, Price: ${self.price:.2f}")

#Subclasses
class Book(Product):
  def __init__(self, product_id , name, price,author):
    super().__init__(product_id,name,price)
    self.author = author
class Clothes(Product):
  def __init__(self,product_id,name,price,size):
    super().__init__(product_id,name,price)
    self.size = size
class Groceries (Product):
  def __init__(self,product_id,name,price,expiry_date):
    super().__init__(product_id,name,price)
    self.expiry_date = expiry_date
class DigitalProduct(Product):
  def __init__ (self, product_id, name, price, file_size):
    super().__init__(product_id, name, price)
    self.file_size = file_size
#_________________________PRODUCT_______________________


#___________________________USER________________________
class User:
  def __init__ (self,username,password):
    self.username = username
    self.password = password
#___________________________USER_________________________


#___________________________CART_________________________
class Cart:
  def __init__(self):
    self.items = []

  def add_item(self,product):
    self.items.append(product)

  def remove_item(self,product_id):
    for item in self.items:
      if item.product_id == product_id:
        self.items.remove(item)
        print(f"Item {product_id} removed from cart.")
        return
    print(f"Item {product_id} not found in cart")

  def check_total(self):
    total = 0
    for item in self.items:
      total += item.price
    return total

  def checkout(self):
    total = self.check_total()
    print(f"Total : ${total}")
    print("Processing payment....")
    print("Checkout successful! Thanks for your purchase 🎁 !")
    self.items.clear()
  #___________________________CART___________________________


#======================================================================
#                            FRONT-END
#======================================================================
#seller lists products
products = [
    Book(101, "Python Book", 25, "John Smith"),
    Clothes(102, "T-Shirt", 20, "L"),
    Groceries(103, "Milk", 4, "2026-12-31"),
    DigitalProduct(104, "Video Course", 70, "2 GB")
  ]


#Storefront: Users have clear prompts to follow
cart = Cart()
while True:
  print("\n================ 😎 GLAMAZON 🤩 ====================")
  print(" 1 ==> View Products " )
  print(" 2 ==> Add Product to Cart " )
  print(" 3 ==> Remove Product from Cart " )
  print(" 4 ==> View Total " )
  print(" 5 ==> Checkout " )
  print(" 6 ==> Exit " )

  choice = input ("Enter an option to start glammin! ")

  #User starts shopping interactively
  # View Products
  if choice == "1":
    print("\n Catalogue:")
    for product in products:
      product.display_product()

  # Add product to cart
  elif choice == "2":
    product_id = int( input("Enter Product ID to add:") )

    found = False
    for product in products:
      if product.product_id == product_id:
        cart.add_item(product)
        print(f"✓{product.name} added to cart.")
        found = True
        break
      if not found:
        print ("❌ Oops! product ID not found!")

  # Remove Product from Cart
  elif choice == "3":
    product_id = int( input("Enter Product ID to remove:") )
    cart.remove_item(product_id)

  # View Total
  elif choice == "4":
    print(f"\n Cart total : ${cart.check_total():.2f}")

  #Checkout
  elif choice == "5":
    cart.checkout()

  #Exit
  elif choice == "6":
    print("Thanks for visiting Glamazon, stay glammin!")
    break

  #Validation : Wrong menu option
  else:
    print ("Invalid option. Please enter a number from the menu")

