# -*- coding: utf-8 -*-
"""Week_01_Python_Basics_Nihal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YGSGpmUpJJhQ9IHfwgU_XXgfveZlrBV1
"""

# ________________________________1.1______________________________________
# Write a Python program that takes any name and age from the user's input.
# It should print like this: "Bob(name) is 21(age) years old
#_________________________________________________________________________

# Take user input
print ("Welcome!")
name = input("Please enter name: ")
age =  int(input("Please enter your age:")) #force age to be a number

# display user input in console
print (f"{name} is {age} years old.")

# ________________________________1.2______________________________________
#             added validation for name and age
#_________________________________________________________________________

print ("Welcome!")

#take name
name = input("Enter name: ").strip()

#validate name
if not name or not name.replace(" ","").isalpha():
  print("Invalid name entered. Please letters only!")
else:
  age_input = input("Enter age: ").strip()   #take age

  if age_input.isdigit():                    #validate age (number)
    age = int(age_input)

    if(age>0):                               #validate age (>0)
      print (f"{name} is {age} years old.")
    else :
      print ("Age must be greater than 0!")

  else:
    print ("invalid age entered.Numbers only please!")

# ________________________________2.1______________________________________
# Write a Python program that takes the user input of your full-name
# and make it a list of separate letters.
# E.g. user entered= ryana
# console = ['r', 'y', 'a', 'n', 'a']
#_________________________________________________________________________

name = input("Enter name: ")
name_list = list(name)
print (name_list)

# ________________________________2.2______________________________________
#                    added validation for name
#_________________________________________________________________________

#take input
print ("Welcome to the letter sieve!")
name = input("Please enter name: ").strip()
print ("Running sieve...")

#validate name
if not name or not name.replace(" ","").isalpha():
  print ("Sieve jammed... letters only!")
else:
  name_list = list(name)
  print(name_list)

# ________________________________2.3______________________________________
#          separated backend and user-facing functionalities
#_________________________________________________________________________

#backend
def letter_sieve(name):
  name_list=list(name)
  print(name_list)

#user interface
name = input("please enter name: ")
letter_sieve(name)

# ________________________________3.1______________________________________
# Write Python program that creates functions based on the following:
# Subtraction function: takes the user input of two values, calculate and print
# their difference
# Multiplication function:  takes the user input of two values,
# calculate and print their product
#_________________________________________________________________________

#substraction
def substraction(num1, num2):
  result = num1 - num2
  print(result)

#multiplication
def multiplication(num1, num2):
  result = num1*num2
  print(result)

#input
num1 = int(input("Enter a number: "))
num2 = int(input("Enter another number: "))

#result
substraction (num1, num2)
multiplication (num1, num2)

# ________________________________3.2______________________________________
# Updated UI elements, user messages and result display more polished
# added method for validation
#_________________________________________________________________________

# ================= BACKEND =====================

def get_number(user_prompt):
  while True:
    value = input(user_prompt)

    if value.lstrip("-").isdigit():
      return int(value)
    else:
      print("Error: Invalid data, please enter numbers only!")

def substract (num1,num2):
  print ("---- Substraction ------")
  print(f"{num1} - {num2} = {num1-num2}")
  print ("------------------------")

def multiply (num1,num2):
  print ("---- Multiplication ----")
  print(f"{num1} * {num2} = {num1*num2}")
  print ("------------------------")

# =============== FRONT-END =====================

print("Welcome to Mathwiz!")

num1 = get_number("Enter 1st number --> ")
num2 = get_number("Enter 2nd number --> ")


print("")
print("Running calculations...")
print("Calculations complete!")
print("")

substract (num1,num2)
print("")
multiply  (num1,num2)

# ________________________________4.1______________________________________
# Write a Python function that takes temperature (in Celcius)
# as function argument and prints:
# -"It’s freezing" if temp ≤ 0
# -"Cold temperature!" if temp is between 1–15
# -"It feels warm." if temp is between 16–25
# -"The weather is very hot!" if temp is above 25
#_________________________________________________________________________

def check_temp(temp):
  if temp <= 0:
    print("It's freezing, stay home!")
  elif temp <= 15 :
    print("It's cold, don't forget your jacket!")
  elif temp <= 25 :
    print("its warm, pack water and sunscreen!")
  elif temp <= 40 :
    print("Hell cannot not hotter than this!")
  elif temp >= 40 :
    print("It's the Apocalypse!")

user_input = int(input("Enter temperature: "))
check_temp(user_input)

# ________________________________5.1______________________________________
# Write a Python program that uses a while loop to help a user log in. It should:
# Asks the user to input the correct password ( "python123")
# Keeps asking the user to enter the correct password
# Prints “Access denied. Please enter the correct password.” when a wrong password is provided.
# Stops ‘while loop’ when the correct password is entered
# Prints "Access Granted" when successful
#_________________________________________________________________________

correct_password = "python123"
user_password = input("Please enter password:")

while (user_password != correct_password):
  print ("Wrong password. Please try again.")
  user_password = input ("Please enter password:")
else:
  print ("Success! Access Granted.")

# ________________________________6.1______________________________________
# Write a Python program that creates a function of multiplication-table.
#It should:
#Take the user input as Function Argument
#Multiply that number from 1 to 10, like:
#Input = 5
#Output = 5 * 1 = 5 ,5 * 2 = 10 ,5 * 3 = 15....5 * 10 = 50
#________________________________________________________________________

num = int(input ("Please enter number to muliply:"))
for i in range(1,11):
  print(f"{num}*{i} = {num*i}")

# ________________________________6.2______________________________________
# polished, separate frontend backend logic
# TBA : add validation to allow numeric inputs only
#__________________________________________________________________________'

#logic
def multiplication_table (num):
  for i in range(1,11):
    print(f"{num}*{i} = {num*i}")

#input
print ("Welcome to TabuLar!")
num = int(input ("Please enter number to muliply --> "))

#display result
print("")
print("=============== MULTIPLICATION TABLE =================")
multiplication_table (num)